---
applications:
- name: initializr-api-dev
  path: ../../src/InitializrApi/bin/Debug/netcoreapp3.1/publish
  buildpacks:
   - dotnet_core_buildpack
  memory: 1024M
  env:
    ASPNETCORE_ENVIRONMENT: Development
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
